### ISSUE TITLE
Long response time after user update

### ISSUE THREAD

**Issue by burnedram** [Hagesjo/decode-web#1]
Hello I am prince from Nigeria and my beautiful daughter use this site called raffedvala.hagesjo.se every day. Much good site we like.

But we have had issues with out of date information, for example it now say 108 days but is not true I was in school just today.

So please mister Hagesjó can you integrate GPS in my phone for automatic update of dvala?

Thank you and also send me 5 000$ so that I can give you 1 973 566 616$

**Comment by Hagesjo** [comment]
We don't negotiate with terrorists :(
